[package]
name = "image_process_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
average = "0.13.1"


[dependencies.kmeans_colors]
version = "0.4.0"
default-features = false
