name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_hello_world:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      run: cargo build --verbose --manifest-path /home/runner/work/Learning-Rust/Learning-Rust/HelloWorld/Cargo.toml
    - name: Build Release
      run: cargo build --verbose --manifest-path /home/runner/work/Learning-Rust/Learning-Rust/HelloWorld/Cargo.toml

    - name: Upload Debug
      uses: actions/upload-artifact@v2
      with:
        name: hello_world_debug
        path: /home/runner/work/Learning-Rust/Learning-Rust/HelloWorld/target/debug

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: hello_world_release
        path: /home/runner/work/Learning-Rust/Learning-Rust/HelloWorld/target/release

  
  build_image_process:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      run: cargo build --verbose --manifest-path /home/runner/work/Learning-Rust/Learning-Rust/image_process/Cargo.toml
   
    - name: Upload Debug
      uses: actions/upload-artifact@v2
      with:
        name: image_process_debug
        path: /home/runner/work/Learning-Rust/Learning-Rust/image_process/target/debug
